### ISSUE TITLE
Add CI

### ISSUE THREAD

**Issue by zanebeckwith** [xaptum/xtt-cpp#2]
Enable travis-ci for continuous integration.

This requires adding a .travis.yml file, and including all the necessary local-build scripts (e.g. locally-building xtt).

The main blocker for this, currently, is getting a working version of Boost on travis.

**Comment by kathrynfejer** [comment]
We are trying to enable testing for xtt-cpp which uses Boost 1.66.0 which requires clang >=5 or gcc >=6 and uses C++14 with CMake 3.11.4 or greater. This is proving to be a difficult task because Travis has very little or extremely outdated support for C and C++ and their libraries. 

Things we fixed and issues we ran into when attempting to fix:
-Changed language to C++ not C 

-Added NIST256 to the AMCL curves used to account for ECDSA changes

-Installed CMake 3.11.4 since the version already downloaded on Travis CI is very old and does not support Boost 1.66.0 which we need. Also appended the /.travis directory to the CMAKE_MODULE_PATH so that FindBoost.cmake could be found by `find_package()`.

-Tried to add Boost with `libboost-all-dev`
--> Travis continued to use boost 1.54 

-Tried to use conan to install Boost
--> Used clang 5.0 and setting for C++14 to be used 
---->Tried to update clang but later realized that should not be necessary for C++14 support. [Build 73](https://travis-ci.com/kathrynfejer/xtt-cpp/builds/80534688) is able to do everything except use the standard library for experimental/optional, signaling that Travis or conan is not properly using C++14.

--> Used and updated gcc to 6.4 within Travis CI using C++14
---->When we run `conan install boost/1.66.0@conan/stable` there are 2 dependencies: bzip2 and zlib. We encounter errors trying to build zlib from source (which is necessary because zlib does not exist for a compiler.version of 6.4). 
---->[Build 113](https://travis-ci.com/kathrynfejer/xtt-cpp/builds/80752220) is able to execute `conan install` properly, but does not update both gcc and g++ versions therefore receiving a mismatch error in the cmake command. Tried to fix this mismatch with an update of both gcc and g++ which asks us to build zlib from source.
---->Attempted to separate zlib and install before gcc was updated, and while Travis showed that zlib was already in the cache it would assert that zlib was missing for the new compiler.version and asked to install zlib from source.
Error produced by zlib built from source: `ERROR: Error downloading file https://zlib.net/zlib-1.2.11.tar.gz: 'HTTPSConnectionPool(host='zlib.net', port=443): Max retries exceeded with url: /zlib-1.2.11.tar.gz (Caused by SSLError(CertificateError("hostname 'zlib.net' doesn't match either of 'adler.madler.net', 'adler.me', 'autodiscover.adler.me', 'autodiscover.saintj.net', 'cpanel.adler.me', 'cpanel.saintj.net', 'mail.adler.me', 'mail.saintj.net', 'saintj.madler.net', 'saintj.net', 'webdisk.adler.me', 'webdisk.saintj.net', 'webmail.adler.me', 'webmail.saintj.net', 'www.adler.madler.net', 'www.adler.me', 'www.saintj.madler.net', 'www.saintj.net'",),))'`

-Tried to use other conan packages besides Conan-center as to avoid zlib
-->When trying to conan install from anywhere but conan-center (adding remote and adjusting settings correctly), we received: `ERROR: Failed requirement 'boost_asio/1.66.0@bincrafters/stable' from 'PROJECT' ` 

We are shelving this issue for the moment and moving forward may try to use with another CI that has better support for C and C++.

**Comment by drbild** [comment]
Just FYI, you can run your builds in a docker container on Travis and avoid all these issues.On Aug 3, 2018 12:35, kathrynfejer <notifications@github.com> wrote:We are trying to enable testing for xtt-cpp which uses Boost 1.66.0 which requires clang >=5 or gcc >=6 and uses C++14 with CMake 3.11.4 or greater. This is proving to be a difficult task because Travis has very little or extremely outdated support for C and C++ and their libraries.
Things we fixed and issues we ran into when attempting to fix:
-Changed language to C++ not C
-Added NIST256 to the AMCL curves used to account for ECDSA changes
-Installed CMake 3.11.4 since the version already downloaded on Travis CI is very old and does not support Boost 1.66.0 which we need. Also appended the /.travis directory to the CMAKE_MODULE_PATH so that FindBoost.cmake could be found by find_package().
-Tried to add Boost with libboost-all-dev
--> Travis continued to use boost 1.54
-Tried to use conan to install Boost
--> Used clang 5.0 and setting for C++14 to be used
---->Tried to update clang but later realized that should not be necessary for C++14 support. Build 73 is able to do everything except use the standard library for experimental/optional, signaling that Travis or conan is not properly using C++14.
--> Used and updated gcc to 6.4 within Travis CI using C++14
---->When we run conan install boost/1.66.0@conan/stable there are 2 dependencies: bzip2 and zlib. We encounter errors trying to build zlib from source (which is necessary because zlib does not exist for a compiler.version of 6.4).
---->Build 113 is able to execute conan install properly, but does not update both gcc and g++ versions therefore receiving a mismatch error in the cmake command. Tried to fix this mismatch with an update of both gcc and g++ which asks us to build zlib from source.
---->Attempted to separate zlib and install before gcc was updated, and while Travis showed that zlib was already in the cache it would assert that zlib was missing for the new compiler.version and asked to install zlib from source.
Error produced by zlib built from source: ERROR: Error downloading file https://zlib.net/zlib-1.2.11.tar.gz: 'HTTPSConnectionPool(host='zlib.net', port=443): Max retries exceeded with url: /zlib-1.2.11.tar.gz (Caused by SSLError(CertificateError("hostname 'zlib.net' doesn't match either of 'adler.madler.net', 'adler.me', 'autodiscover.adler.me', 'autodiscover.saintj.net', 'cpanel.adler.me', 'cpanel.saintj.net', 'mail.adler.me', 'mail.saintj.net', 'saintj.madler.net', 'saintj.net', 'webdisk.adler.me', 'webdisk.saintj.net', 'webmail.adler.me', 'webmail.saintj.net', 'www.adler.madler.net', 'www.adler.me', 'www.saintj.madler.net', 'www.saintj.net'",),))'
-Tried to use other conan packages besides Conan-center as to avoid zlib
-->When trying to conan install from anywhere but conan-center (adding remote and adjusting settings correctly), we received: ERROR: Failed requirement 'boost_asio/1.66.0@bincrafters/stable' from 'PROJECT'
We are shelving this issue for the moment and moving forward may try to use with another CI that has better support for C and C++.

**Comment by zanebeckwith** [comment]
Ha, well, that's a mentoring failure on my part. Sorry, Kathryn, that I led you down the wrong path.
